# For the first time please clone the TPM repository, <leader>I to install:
# git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm

set -g prefix C-Space
unbind C-b

unbind r
bind r source-file ~/.config/tmux/tmux.conf

set -g mouse on

# act like vim
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# start pane numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# Configure the catppuccin plugin
set -ogq @catppuccin_status_left_separator ""

set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "slanted"
set -g @catppuccin_window_text " #W #[fg=#{@thm_yellow},bg=#{@thm_surface_0}]#F"
set -g @catppuccin_window_current_text " #W #[fg=#{@thm_yellow},bg=#{@thm_surface_1}]#F"

set -g @catppuccin_status_weather_icon_bg "#4e6d4f" 
set -g @catppuccin_status_cpu_icon_bg "#4e6d4f" 
set -g @catppuccin_status_date_time_icon_bg "#4e6d4f" 

# load catppuccin theme ...
run '~/.config/tmux/plugins/tmux/catppuccin.tmux'

# Tmux Plugin Manager
set -g @plugin "tmux-plugins/tpm"

# Selected Plugins
set -g @plugin "christoomey/vim-tmux-navigator"
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'xamut/tmux-weather'
set -g @plugin "tmux-plugins/tmux-yank"
set -g @plugin "tmux-plugins/tmux-sensible"
set -g @plugin "NHDaly/tmux-better-mouse-mode"

set -g status-position top

set -g status-right-length 100
set -g status-left-length 100

set-option -g @tmux-weather-location "Ottawa,Ontario"
set -g  @catppuccin_date_time_text " %h %d %H:%M"
set -g  status-left  "#{E:@catppuccin_status_session}#[fg=#{@thm_yellow},bg=#{@thm_mantle}]  "
set -gF status-right "#{E:@catppuccin_status_weather}#{E:@catppuccin_status_cpu}#{E:@catppuccin_status_date_time}"

### ensure tmux-cpu runs every second
set -g status-interval 1

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "~/.config/tmux/plugins/tpm/tpm"

